language: python
python:
- '2.7'
- '3.3'
- pypy
deploy:
  password:
    secure: cGEruM74c8F9Y7WrltHMXoWSkoAsrotxcsbHfD3a1pMNdq7SXUs+kHxT45pgFalD70thbwaF+aURZNdd7f7Xel8YWX0fFNp2Acc3h07X+1l9K9lVZSA9f5twH75/31TgCGNwwSc4IalFlvlaXa8Fig2+0HwIev1Y2PU3MPsH/PXBVQCZBpMlicY7oabaHUD6gAC1npcbsuoJmUG5ETGQdPCnOvBjxamQUEJukPlO+A1SRoAaC2N99pis2DJmm2f9szYSUg0hc84y21RCaAI3LyCnrrD5vdzesG4sYH0YEoa8WFkBwvmD1xPlG2jpvYk2loregrB+wjPveIUau7GWYi5xokD7PW9AF6gcBeWqMhDMg/sNB2vmrHbrIVsNfY+t1ObdOkbqIDER/Driv6BxxD0HNFTnf+R74CtFoootTZUfHADrR6GtdgWlflPoJ3CeeMYAERvF1jtKMldPW1ISzXCyJ6IbF5LY0/3YgQYQGGZXqIZv+yfuR4iAohPkyLl7VSqWLltQjN605FxvwPac6AW/owNFtAO0rWWA0jH1I+eVp0E8OsQHHtbY8Iv3cfZu8ds5YQ6s4lPLjYbMPlXsEYW4GrLly+OrfWtTOjjo1vLZgYPYqgvFupr5MCcGrYiPRUfvYYjU2ONz5kxFSFjzNAfUoGqMVC0dG3N8svcIwG0=
